services:
  aasx-server:
    container_name: aasx-server
    hostname: aasx-server
    image: adminshellio/aasx-server-blazor-for-demo:v3latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./aasxs:/usr/share/aasxs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - ENV ASPNETCORE_URLS=http://+:5001
      - ENV ASPNETCORE_HTTP_PORTS=5001
    command: --start-index 0 --no-security --edit --data-path /usr/share/aasxs --external-blazor http://localhost:5001
